services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: asterra-postgres
    environment:
      POSTGRES_DB: asterra_db
      POSTGRES_USER: asterra_user
      POSTGRES_PASSWORD: localstack_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
