services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: asterra-postgres
    environment:
      POSTGRES_DB: asterra_db
      POSTGRES_USER: asterra_user
      POSTGRES_PASSWORD: localstack_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: asterra-processor:latest
    container_name: asterra-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: asterra_db
      DB_USER: asterra_user
      DB_PASSWORD: localstack_pass
      S3_ENDPOINT: http://host.gateway.internal:4566
      AWS_REGION: us-east-1
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  postgres_data:
